### ISSUE TITLE
Implement Draft.js component

### ISSUE THREAD

**Issue by aahutsal** [aahutsal/arweave-open-knowledge#6]
Add `draft.js` as custom view. Make sure it saves article to `localStorage`
Please, merge with `origin/agutsal` branch. It has Login/Logout fixed.

**Comment by janus** [comment]
https://github.com/janus/arweave-open-knowledge/tree/janus_knowledge
Added text editor

**Comment by aahutsal** [comment]
a7e7ecf3801461d48cd6b482e8e9755debd58625 closes #6
